### ISSUE TITLE
Please example breadcrumbs for `param, query router`?

### ISSUE THREAD

**Issue by thearabbit** [jypblue/vue-crumbs#2]
Please example breadcrumbs for `param, query router`?

**Comment by jypblue** [comment]
i can't understand what do you mean?  `param,query router` ?

**Comment by thearabbit** [comment]
Yes, it my route have `params and query`?

**Comment by jypblue** [comment]
if your route have param and query  means that it jump to different pages, right?

**Comment by jypblue** [comment]
i understand , i think you can config the breadcrumbs as variables,. you can change the variables by comparing parameters in `router.beforeEach`  , and then assigns the variable to breadcrumbs

**Comment by jypblue** [comment]
@thearabbit 
you can config route by the README.md
